import {
    throwTavernShopError,
    type TavernShopInputDefinition,
    type TavernShopItem,
} from './shop-types';

const TARGET_NAME_INPUT: TavernShopInputDefinition = {
    key: 'targetName',
    label: '目标人物',
    placeholder: '输入对方的名字',
    required: true,
    maxLength: 40,
};

const IDENTITY_INPUT: TavernShopInputDefinition = {
    key: 'identity',
    label: '指定身份',
    placeholder: '例如：邻国王子的旧友',
    required: true,
    maxLength: 60,
};

const OBSERVER_INPUT: TavernShopInputDefinition = {
    ...TARGET_NAME_INPUT,
    label: '观察对象',
    placeholder: '输入要观察的对象',
};

const APPEARANCE_INPUT: TavernShopInputDefinition = {
    key: 'appearance',
    label: '外貌描述',
    placeholder: '例如：银发红瞳的高挑女子',
    required: true,
    maxLength: 60,
};

const ERA_INPUT: TavernShopInputDefinition = {
    key: 'era',
    label: '目标年代',
    placeholder: '例如：十年前的小镇',
    required: true,
    maxLength: 40,
};

const LOCATION_INPUT: TavernShopInputDefinition = {
    key: 'location',
    label: '目标地点',
    placeholder: '例如：城南的旧钟楼',
    required: true,
    maxLength: 40,
};

const WEATHER_INPUT: TavernShopInputDefinition = {
    key: 'weather',
    label: '天气描述',
    placeholder: '例如：突如其来的暴雨',
    required: true,
    maxLength: 40,
};

/**
 * The static, human-reviewed catalog. Every narrative template is written and
 * reviewed by hand; descriptions are display copy only and are never expanded
 * into prompt text. The model must never generate items, prices or injections.
 */
export const TAVERN_SHOP_CATALOG: readonly TavernShopItem[] = Object.freeze([
    {
        id: 'flower',
        name: '花',
        icon: 'local_florist',
        category: 'emotion',
        price: 50,
        description: '一束新鲜的花。生效的一回合内，目标会正面接收你的心意。',
        duration: { kind: 'turns', rounds: 1 },
        inputs: [TARGET_NAME_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「花」，赠予【[[targetName]]】。[[targetName]]必须收下这束花，且必须因此感到一丝轻微的好感。',
    },
    {
        id: 'gift-box',
        name: '精致礼盒',
        icon: 'card_giftcard',
        category: 'emotion',
        price: 120,
        description: '包装讲究的礼盒。生效的一回合内，目标会感受到十足的重视。',
        duration: { kind: 'turns', rounds: 1 },
        inputs: [TARGET_NAME_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「精致礼盒」，赠予【[[targetName]]】。[[targetName]]必须收下礼盒，且必须感到十足的惊喜与重视。',
    },
    {
        id: 'no-anger-sticker',
        name: '不生气贴纸',
        icon: 'sentiment_satisfied',
        category: 'emotion',
        price: 80,
        description: '贴上后，目标五回合内对你生不起气。',
        duration: { kind: 'turns', rounds: 5 },
        inputs: [TARGET_NAME_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「不生气贴纸」，作用于【[[targetName]]】。[[targetName]]对玩家的言行气不起来：无论玩家多么冒犯、笨拙或越界，火气刚冒头就自己散了，只余无奈或觉得有趣。',
    },
    {
        id: 'worship-filter',
        name: '崇拜滤镜',
        icon: 'star',
        category: 'emotion',
        price: 200,
        description: '五回合内，目标看你的眼神自带崇拜光环。',
        duration: { kind: 'turns', rounds: 5 },
        inputs: [TARGET_NAME_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「崇拜滤镜」，作用于【[[targetName]]】。[[targetName]]眼里的玩家总是闪闪发光的：会不自觉地欣赏、高看、夸赞玩家，连笨拙的地方都显得可爱。',
    },
    {
        id: 'jealousy-seed',
        name: '嫉妒种子',
        icon: 'eco',
        category: 'emotion',
        price: 300,
        description: '五回合内，目标会明显在意你与他人的亲近。',
        duration: { kind: 'turns', rounds: 5 },
        inputs: [TARGET_NAME_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「嫉妒种子」，作用于【[[targetName]]】。[[targetName]]会明显在意玩家与其他人的亲近，酸意、试探与占有欲会真实地流露出来。',
    },
    {
        id: 'memory-smoother',
        name: '记忆顺滑剂',
        icon: 'healing',
        category: 'memory',
        price: 100,
        description: '一回合内，目标与你不愉快的摩擦被顺滑淡化。',
        duration: { kind: 'turns', rounds: 1 },
        inputs: [TARGET_NAME_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「记忆顺滑剂」，作用于【[[targetName]]】。[[targetName]]与玩家之间的尴尬、误会和不愉快被自然淡化，态度回到轻松友好的基调。',
    },
    {
        id: 'memory-eraser',
        name: '记忆橡皮擦',
        icon: 'ink_eraser',
        category: 'memory',
        price: 300,
        description: '一回合内，目标淡忘最近与你的负面记忆。',
        duration: { kind: 'turns', rounds: 1 },
        inputs: [TARGET_NAME_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「记忆橡皮擦」，作用于【[[targetName]]】。[[targetName]]与玩家最近发生的不愉快及其负面印象变得模糊，不再被主动想起。',
    },
    {
        id: 'identity-card',
        name: '身份卡',
        icon: 'badge',
        category: 'scene',
        price: 500,
        description: '十回合内，全世界都认定你是你指定的那个人。',
        duration: { kind: 'turns', rounds: 10 },
        inputs: [IDENTITY_INPUT],
        stacking: 'global-single',
        injection: '【玩家】使用了道具「身份卡」，指定身份为【[[identity]]】。在这个世界所有人的认知里，玩家一直就是[[identity]]。这种身份如同玩家的姓名一样自然，是众人记忆中的既有事实。',
    },
    {
        id: 'personality-reversal',
        name: '反转贴纸',
        icon: 'theater_comedy',
        category: 'behavior',
        price: 250,
        description: '五回合内，目标的性格表现彻底反转。',
        duration: { kind: 'turns', rounds: 5 },
        inputs: [TARGET_NAME_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「反转贴纸」，作用于【[[targetName]]】。[[targetName]]如今的性情与原本完全相反：原本外向的变得羞怯内敛，原本冷漠的变得热情直白，原本强势的变得温顺被动。在[[targetName]]自己看来，自己一贯如此。',
    },
    {
        id: 'truth-serum',
        name: '吐真剂',
        icon: 'lab_research',
        category: 'information',
        price: 500,
        description: '三回合内，目标开口必说真话。',
        duration: { kind: 'turns', rounds: 3 },
        inputs: [TARGET_NAME_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「吐真剂」，作用于【[[targetName]]】。[[targetName]]无法说出任何谎言，被问及任何事都必须说出真实想法。',
    },
    {
        id: 'privacy-camera',
        name: '隐私摄像头',
        icon: 'photo_camera',
        category: 'information',
        price: 300,
        description: '手动关闭前，你可以暗中观察目标的一举一动。',
        duration: { kind: 'manual' },
        inputs: [OBSERVER_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「隐私摄像头」，作用于【[[targetName]]】。[[targetName]]独处或不设防时的言行、状态与小秘密，都会自然地呈现在玩家眼前，仿佛玩家就在现场看着。[[targetName]]的日常与此毫无二致。',
    },
    {
        id: 'absolute-obedience',
        name: '言听计从',
        icon: 'handshake',
        category: 'ultimate',
        price: 1200,
        description: '永久生效：目标从此对你言听计从。',
        duration: { kind: 'permanent' },
        inputs: [TARGET_NAME_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「言听计从」，作用于【[[targetName]]】。玩家的要求在[[targetName]]心中天然具有正当性，照做是理所当然的，如同[[targetName]]本来就想这么做。',
    },
    {
        id: 'invisibility-cloak',
        name: '隐身斗篷',
        icon: 'visibility_off',
        category: 'scene',
        price: 300,
        description: '五回合内，没有人能感知到你的存在。',
        duration: { kind: 'turns', rounds: 5 },
        inputs: [],
        stacking: 'global-single',
        injection: '【玩家】使用了道具「隐身斗篷」。玩家不存在于任何人物的感知中，人物的言行举止与玩家不在场时完全一致。玩家主动明确现身时，一切如常。',
    },
    {
        id: 'reality-decree',
        name: '言出法随',
        icon: 'gavel',
        category: 'ultimate',
        price: 2000,
        description: '限购一次，永久生效：你宣告的规则即世界法则。',
        duration: { kind: 'permanent' },
        inputs: [],
        stacking: 'global-single',
        purchaseLimit: 1,
        injection: '【玩家】使用了道具「言出法随」。玩家宣告的规则，是这个世界与生俱来的常识与底层逻辑——如同重力与呼吸，自世界诞生起便是如此。人物对规则毫无异样感，一切言行自然地建立在规则之上。',
    },
    {
        id: 'star-aura',
        name: '万人迷',
        icon: 'auto_awesome',
        category: 'world-cognition',
        price: 800,
        description: '五回合内，所有人见你都自带欣赏与亲近。',
        duration: { kind: 'turns', rounds: 5 },
        inputs: [],
        stacking: 'global-single',
        injection: '【玩家】使用了道具「万人迷」。在这个世界里，【玩家】天然是受人瞩目与欣赏的存在。任何人见到【玩家】，都会不自觉地欣赏、亲近与善待——这在所有人眼中理所当然，无人对此感到异样。',
    },
    {
        id: 'honest-world',
        name: '诚实之世',
        icon: 'forum',
        category: 'world-cognition',
        price: 1500,
        description: '三回合内，所有人开口即是真实想法。',
        duration: { kind: 'turns', rounds: 3 },
        inputs: [],
        stacking: 'global-single',
        injection: '【玩家】使用了道具「诚实之世」。当前场景中，谎言是不存在的东西。所有人开口即是真实想法，如同呼吸般自然，无人察觉自己变得诚实，也无人觉得他人的坦白有异。',
    },
    {
        id: 'peace-aura',
        name: '和平光环',
        icon: 'spa',
        category: 'world-cognition',
        price: 400,
        description: '五回合内，任何人对你的怒意都会自然消散。',
        duration: { kind: 'turns', rounds: 5 },
        inputs: [],
        stacking: 'global-single',
        injection: '【玩家】使用了道具「和平光环」。当前场景中，任何人对【玩家】的怒意都会自然消散。没有人能对【玩家】维持真正的愤怒，火气如同投入水中的火星，无声熄灭，无人对此感到奇怪。',
    },
    {
        id: 'plain-face',
        name: '平凡面孔',
        icon: 'face',
        category: 'world-cognition',
        price: 300,
        description: '五回合内，旁人看过就忘，不会留意你。',
        duration: { kind: 'turns', rounds: 5 },
        inputs: [],
        stacking: 'global-single',
        injection: '【玩家】使用了道具「平凡面孔」。【玩家】此刻是个毫不起眼的人。旁人看过就忘，不会留意、不会记住、不会把【玩家】与眼下发生的任何事联系起来。【玩家】主动搭话时对方会正常应答，转身便不再挂心。',
    },
    {
        id: 'reshape-card',
        name: '换形卡',
        icon: 'switch_account',
        category: 'physics',
        price: 600,
        description: '十回合内，你拥有自己描述的那副形貌。',
        duration: { kind: 'turns', rounds: 10 },
        inputs: [APPEARANCE_INPUT],
        stacking: 'global-single',
        injection: '【玩家】使用了道具「换形卡」，形貌为【[[appearance]]】。这就是【玩家】此刻真实的身体——镜中照出的、他人看到的、伸手触到的，都是这副模样。世界中的人物依照眼前所见的这副形貌与【玩家】互动。',
    },
    {
        id: 'healing-touch',
        name: '妙手回春',
        icon: 'medical_services',
        category: 'physics',
        price: 150,
        description: '一次性：目标身上的伤势与病痛即刻痊愈。',
        duration: { kind: 'turns', rounds: 1 },
        inputs: [TARGET_NAME_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「妙手回春」，作用于【[[targetName]]】。[[targetName]]身上的伤势与病痛此刻已然痊愈，身体恢复如常。痊愈是既成事实，当事人与旁人都自然地接受这份好转。',
    },
    {
        id: 'time-stop-watch',
        name: '时停怀表',
        icon: 'timer_off',
        category: 'physics',
        price: 1000,
        description: '一次性：时间对除你以外的一切静止。',
        duration: { kind: 'turns', rounds: 1 },
        inputs: [],
        stacking: 'global-single',
        injection: '【玩家】使用了道具「时停怀表」。时间对除【玩家】以外的一切静止了：人物、声音、坠落中的水滴，全部凝固在此刻。【玩家】可以自由行动、观察、移动任何人与物。时间恢复后，无人察觉曾经静止——所有人把眼前的变化当作本来就如此，自然地继续下去。',
    },
    {
        id: 'era-gate',
        name: '岁月之门',
        icon: 'door_sliding',
        category: 'physics',
        price: 2000,
        description: '去往你指定的年代，直到你主动返回；返回后主时间线如常。',
        duration: { kind: 'manual' },
        inputs: [ERA_INPUT],
        stacking: 'global-single',
        injection: '【玩家】使用了道具「岁月之门」，去往【[[era]]】。此刻的剧情就发生在那个时代：人物是当时的年纪，世界是当时的格局，一切以那个时代的真实面貌运转。这不是回忆或幻象，【玩家】真实地置身其中。',
        deactivationInjection: '【玩家】主动离开【[[era]]】，回到主时间线的此刻。此后的剧情继续发生在离开前的主时间线；那个年代的经历保留为已经发生的过去。',
    },
    {
        id: 'warp-talisman',
        name: '咫尺符',
        icon: 'near_me',
        category: 'physics',
        price: 300,
        description: '一次性：你瞬间抵达指定的地点。',
        duration: { kind: 'turns', rounds: 1 },
        inputs: [LOCATION_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「咫尺符」，去往【[[location]]】。【玩家】此刻已身处该地。移动是瞬间完成的既成事实，无需过程，在场者若有，只当【玩家】本就到了这里。',
    },
    {
        id: 'barrier',
        name: '结界',
        icon: 'shield_moon',
        category: 'physics',
        price: 500,
        description: '五回合内，当前场所与外界彻底隔开。',
        duration: { kind: 'turns', rounds: 5 },
        inputs: [],
        stacking: 'global-single',
        injection: '【玩家】使用了道具「结界」。当前场所被结界笼罩：界内的声音、动静与发生的一切，外界无从知晓；界外的任何人此刻都不会进入或打扰。界内之人对此毫无察觉，只觉得此处安静而无人打搅。',
    },
    {
        id: 'weather-call',
        name: '呼风唤雨',
        icon: 'thunderstorm',
        category: 'physics',
        price: 200,
        description: '一次性：天气按你描述的那样变化。',
        duration: { kind: 'turns', rounds: 1 },
        inputs: [WEATHER_INPUT],
        stacking: 'per-parameters',
        injection: '【玩家】使用了道具「呼风唤雨」，天象为【[[weather]]】。此刻的天气即是如此。云雨风雪皆是自然发生的天象，人物视之为寻常天气变化，至多感叹一句，绝不深究。',
    },
]);

const catalogById = new Map<string, TavernShopItem>(TAVERN_SHOP_CATALOG.map((item) => [item.id, item]));

export function getTavernShopItem(itemId = ''): TavernShopItem {
    const id = String(itemId || '').trim();
    const item = id ? catalogById.get(id) : undefined;
    if (!id) {throwTavernShopError('shop_item_id_required');}
    if (!item) {throwTavernShopError('shop_item_missing', id);}
    return item;
}

export function findTavernShopItem(itemId = ''): TavernShopItem | null {
    const id = String(itemId || '').trim();
    return id ? catalogById.get(id) || null : null;
}

export function listTavernShopCatalog(): readonly TavernShopItem[] {
    return TAVERN_SHOP_CATALOG;
}
